### PR TITLE
Adding variable to allow selection of template

### PR DESCRIPTION
**Pull request by zahillmtu**

### CODE REVIEW

**Comment by zahillmtu** [comment]
I have a second commit where I deleted the other template. The original one is still in there, I never removed it. All set?

**Comment by mrodden** [comment]
Can you squash the 3 commits into one? I can do it when I do the pull request if not.

**Comment by zahillmtu** [comment]
I squashed them I believe, I've never done it before so if it's not right please let me know.

**Comment by mrodden** [comment]
Merged manually.

**Pull request closed without merging**
